/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DisciplerRouteImport } from './routes/_discipler'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as DisciplerIndexRouteImport } from './routes/_discipler/index'
import { Route as AdminDisciplesRouteImport } from './routes/admin/disciples'
import { Route as AdminChecklistsRouteImport } from './routes/admin/checklists'
import { Route as DisciplerMeetingsRouteImport } from './routes/_discipler/meetings'
import { Route as DisciplerDisciplesIndexRouteImport } from './routes/_discipler/disciples.index'
import { Route as DisciplerDisciplesIdRouteImport } from './routes/_discipler/disciples.$id'

const DisciplerRoute = DisciplerRouteImport.update({
  id: '/_discipler',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const DisciplerIndexRoute = DisciplerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DisciplerRoute,
} as any)
const AdminDisciplesRoute = AdminDisciplesRouteImport.update({
  id: '/disciples',
  path: '/disciples',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminChecklistsRoute = AdminChecklistsRouteImport.update({
  id: '/checklists',
  path: '/checklists',
  getParentRoute: () => AdminRouteRoute,
} as any)
const DisciplerMeetingsRoute = DisciplerMeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => DisciplerRoute,
} as any)
const DisciplerDisciplesIndexRoute = DisciplerDisciplesIndexRouteImport.update({
  id: '/disciples/',
  path: '/disciples/',
  getParentRoute: () => DisciplerRoute,
} as any)
const DisciplerDisciplesIdRoute = DisciplerDisciplesIdRouteImport.update({
  id: '/disciples/$id',
  path: '/disciples/$id',
  getParentRoute: () => DisciplerRoute,
} as any)

export interface FileRoutesByFullPath {
  '/admin': typeof AdminRouteRouteWithChildren
  '/': typeof DisciplerIndexRoute
  '/meetings': typeof DisciplerMeetingsRoute
  '/admin/checklists': typeof AdminChecklistsRoute
  '/admin/disciples': typeof AdminDisciplesRoute
  '/admin/': typeof AdminIndexRoute
  '/disciples/$id': typeof DisciplerDisciplesIdRoute
  '/disciples/': typeof DisciplerDisciplesIndexRoute
}
export interface FileRoutesByTo {
  '/meetings': typeof DisciplerMeetingsRoute
  '/admin/checklists': typeof AdminChecklistsRoute
  '/admin/disciples': typeof AdminDisciplesRoute
  '/': typeof DisciplerIndexRoute
  '/admin': typeof AdminIndexRoute
  '/disciples/$id': typeof DisciplerDisciplesIdRoute
  '/disciples': typeof DisciplerDisciplesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/admin': typeof AdminRouteRouteWithChildren
  '/_discipler': typeof DisciplerRouteWithChildren
  '/_discipler/meetings': typeof DisciplerMeetingsRoute
  '/admin/checklists': typeof AdminChecklistsRoute
  '/admin/disciples': typeof AdminDisciplesRoute
  '/_discipler/': typeof DisciplerIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/_discipler/disciples/$id': typeof DisciplerDisciplesIdRoute
  '/_discipler/disciples/': typeof DisciplerDisciplesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/admin'
    | '/'
    | '/meetings'
    | '/admin/checklists'
    | '/admin/disciples'
    | '/admin/'
    | '/disciples/$id'
    | '/disciples/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/meetings'
    | '/admin/checklists'
    | '/admin/disciples'
    | '/'
    | '/admin'
    | '/disciples/$id'
    | '/disciples'
  id:
    | '__root__'
    | '/admin'
    | '/_discipler'
    | '/_discipler/meetings'
    | '/admin/checklists'
    | '/admin/disciples'
    | '/_discipler/'
    | '/admin/'
    | '/_discipler/disciples/$id'
    | '/_discipler/disciples/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  DisciplerRoute: typeof DisciplerRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_discipler': {
      id: '/_discipler'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DisciplerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_discipler/': {
      id: '/_discipler/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DisciplerIndexRouteImport
      parentRoute: typeof DisciplerRoute
    }
    '/admin/disciples': {
      id: '/admin/disciples'
      path: '/disciples'
      fullPath: '/admin/disciples'
      preLoaderRoute: typeof AdminDisciplesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/checklists': {
      id: '/admin/checklists'
      path: '/checklists'
      fullPath: '/admin/checklists'
      preLoaderRoute: typeof AdminChecklistsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_discipler/meetings': {
      id: '/_discipler/meetings'
      path: '/meetings'
      fullPath: '/meetings'
      preLoaderRoute: typeof DisciplerMeetingsRouteImport
      parentRoute: typeof DisciplerRoute
    }
    '/_discipler/disciples/': {
      id: '/_discipler/disciples/'
      path: '/disciples'
      fullPath: '/disciples/'
      preLoaderRoute: typeof DisciplerDisciplesIndexRouteImport
      parentRoute: typeof DisciplerRoute
    }
    '/_discipler/disciples/$id': {
      id: '/_discipler/disciples/$id'
      path: '/disciples/$id'
      fullPath: '/disciples/$id'
      preLoaderRoute: typeof DisciplerDisciplesIdRouteImport
      parentRoute: typeof DisciplerRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminChecklistsRoute: typeof AdminChecklistsRoute
  AdminDisciplesRoute: typeof AdminDisciplesRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminChecklistsRoute: AdminChecklistsRoute,
  AdminDisciplesRoute: AdminDisciplesRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface DisciplerRouteChildren {
  DisciplerMeetingsRoute: typeof DisciplerMeetingsRoute
  DisciplerIndexRoute: typeof DisciplerIndexRoute
  DisciplerDisciplesIdRoute: typeof DisciplerDisciplesIdRoute
  DisciplerDisciplesIndexRoute: typeof DisciplerDisciplesIndexRoute
}

const DisciplerRouteChildren: DisciplerRouteChildren = {
  DisciplerMeetingsRoute: DisciplerMeetingsRoute,
  DisciplerIndexRoute: DisciplerIndexRoute,
  DisciplerDisciplesIdRoute: DisciplerDisciplesIdRoute,
  DisciplerDisciplesIndexRoute: DisciplerDisciplesIndexRoute,
}

const DisciplerRouteWithChildren = DisciplerRoute._addFileChildren(
  DisciplerRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AdminRouteRoute: AdminRouteRouteWithChildren,
  DisciplerRoute: DisciplerRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
